control:
  ros__parameters:
    # Trajectory parameters
    radius: 4.0 # meter
    altitude: 3.0 # meter
    omega: 0.25 # rad/s

    # Duration to hover after takeoff before starting the circle (in seconds)
    hover_duration: 5.0

    # Descent rate during the offboard landing sequence (in m/s, positive value)
    landing_descent_rate: 0.5